"""seed data

Revision ID: 9c1410f2d0f5
Revises: a175d3247dbc
Create Date: 2025-05-26 05:11:11.023114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1410f2d0f5'
down_revision = 'a175d3247dbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
